"""update_deadlines_to_array

Revision ID: 346fe622007f
Revises: 09843a8ffa06
Create Date: 2025-07-16 17:52:53.035566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346fe622007f'
down_revision: Union[str, Sequence[str], None] = '09843a8ffa06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deadlines', 'files', ['file_id'], ['id'])
    # Convert deadlines column from TEXT to VARCHAR[] using PostgreSQL USING clause
    op.execute("ALTER TABLE files ALTER COLUMN deadlines TYPE VARCHAR[] USING string_to_array(deadlines, ', ')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert deadlines column back from VARCHAR[] to TEXT
    op.execute("ALTER TABLE files ALTER COLUMN deadlines TYPE TEXT USING array_to_string(deadlines, ', ')")
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    # ### end Alembic commands ###
