"""add_tags_to_files

Revision ID: 491dc64729ce
Revises: 346fe622007f
Create Date: 2025-07-16 20:57:34.988530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '491dc64729ce'
down_revision: Union[str, Sequence[str], None] = '346fe622007f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.alter_column('files', 'deadlines',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'deadlines',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('files', 'tags')
    # ### end Alembic commands ###
