"""Add content_hash to files

Revision ID: b241c4cec8e4
Revises: 7256d53d13c2
Create Date: 2025-07-21 15:00:36.090447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b241c4cec8e4'
down_revision: Union[str, Sequence[str], None] = '7256d53d13c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['id'])
    op.create_unique_constraint(None, 'deadlines', ['id'])
    op.add_column('files', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_content_hash'), 'files', ['content_hash'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_files_content_hash'), table_name='files')
    op.drop_column('files', 'content_hash')
    op.drop_constraint(None, 'deadlines', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
